//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ngram
    {
        public string token { get; set; }
        public string file_name { get; set; }
        public int id { get; set; }

        public override int GetHashCode()
        {
            return (token + " ->" + file_name).GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if (obj == null || !(obj is Ngram)) return false;

            var other = (Ngram)obj;
            return token.Equals(other.token) && file_name.Equals(other.file_name);
        }
    }
}
